FROM erlang:20.2

RUN apt-get update
RUN apt-get install -y dnsutils

RUN mkdir -p /opt/beamcoin
WORKDIR /opt/beamcoin

## Fetch / Compile deps
ADD rebar.config rebar.config
ADD rebar.lock rebar.lock

RUN rebar3 get-deps
RUN rebar3 compile

## Add / Compile source
ADD src/ src/
RUN rebar3 compile

CMD GEN="$(dig +short beamcoin)" &&  erl -noinput -noshell -name test@127.0.0.1 -pa _build/default/lib/*/ebin -s lager -run beamcoin start_link satoshi@127.0.0.1-genesis.block /ip4/$GEN/tcp/8333
